#!/bin/sh
# vim: ts=4: shiftwidth=4:

##
# drist --
# A tool to configure and synchronize configurations to, and/or run
# scripts on remote host(s) via scp(1) and ssh(1). Privilege escalation
# through sudo and an encrypted secrets file.
#
# SYNOPSIS
# drist [-p] [-d] [-e] [-S script] [-f files-directory] [-F file-to-copy] destination [...]
#
# -----------------------------------------------------------------------------
# Copyright (c) 2018, Rapenne Solène
# Copyright (c) 2025, John Kaul
# Copyright (c) 2026, John Kaul, Todd Greenwood
# All rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
# -----------------------------------------------------------------------------

# ---[ GLOBALS ]--------------------------------------------------
COPY_FILE=""                           # default single file to copy.
CURRENT_SERVER=""                      # current server
EXEC='exec sh -c'                      # POSIX‑compliant shell.
SSHONCE=0                              # set up a socket for persistent connection.
SSH_PARAMS=""                          # default ssh parameters.
TEMPDIR=".drist_files_XXXXXXXXXXXXXXX" # tempdir created on remote by create_temp
TRUNCATE=0                             # Remove the domain name from the hostname.
USE_DIR="files"                        # default directory to upload if no optional switches.
USE_FILE="script"                      # default script file to upload if no optional switches.

# ---[ HELPERS ]--------------------------------------------------
##
# usage --
# @brief displays usage information.
usage() {
    echo "$0 v2.06"
    echo "$0 [-p] [-d] [-S script-to-run] [-f files-to-copy-directory] [-F single-file-to-copy] [-T tempdir] destination [...]"
    exit 0
}


##
# copy_files --
# @brief Copy directory to a remote server.
#
# Parameters:
#   $1 - source directory
#   $2 - remote server name
#   $3 - remote temporary directory
copy_files() {
    src_dir=$1
    remote_server=$2
    remote_tmp=$3

    if [ -d "${src_dir}" ]; then
        ssh $SSH_PARAMS "${remote_server}" "mkdir -p ${remote_tmp}"
        tar cf - -C . . | ssh $SSH_PARAMS "${remote_server}" 'tar xf - -C '"${remote_tmp}"
    fi
    set x
}


##
# copy_single_file --
# @brief Copy a single file from a local directory to a remote server.
#
# Parameters:
#   $1 - source file
#   $2 - remote server name
#   $3 - remote temporary directory
copy_single_file() {
    src_file=$1
    remote_server=$2
    remote_tmp=$3

    if [ -f "${src_file}" ]; then
        ssh $SSH_PARAMS "${remote_server}" "mkdir -p ${remote_tmp}"
        tar cf - -C . . | ssh $SSH_PARAMS "${remote_server}" 'tar xf - -C '"${remote_tmp}"
    fi
}

##
# remote_script --
# @brief Execute a script on a remote host.
#
# Parameters:
#   $1 - script file
#   $2 - remote server name
#   $3 - remote temporary directory
remote_script() {
    script_file=$1
    remote_server=$2
    remote_tmp=$3
    FILE=$(basename -- "$script_file")

	ssh $SSH_PARAMS "${remote_server}" "
		cd \"${remote_tmp}\" && \
		cat - > \"${FILE}\" && \
		chmod +x \"${FILE}\" && \
		${EXEC} \"./${FILE}\"" <"$script_file"
}

# delete_temp --
# @brief Deletes temporary directory on remote host.
#
# Parameters:
#   $1 - remote server name
#   $2 - remote temporary directory
delete_temp() {
    remote_server=$1
    remote_tmp=$2

    if [ "${remote_tmp}" != "" ]; then
        ssh $SSH_PARAMS "$remote_server" "rm -rf ${remote_tmp}"
    fi
}

# ---[ ARGUMENT PARSER ]------------------------------------------
# (custom getopt() like argument parser)

# check to see if we have enough arguments.
if [ $# -lt 1 ]; then echo "Not enough arguments."; fi

# flag to set when done processing arguments.
done_options=

##
# more_options --
# @brief Check whether there are more options left to parse.
#
# Returns:
#   0 if there are more options, 1 otherwise.
more_options() {
    test $done_options && return 1
    [ $# -eq 0 ] && return 1
    case "$1" in
    --) return 1 ;; # end of options
    -*) return 0 ;; # still an option
    *) return 1 ;;  # non‑option argument
    esac
}

# -------------------------------------------------------------------------
# Parse command‑line arguments.
# -------------------------------------------------------------------------
while more_options "$1"; do
    case "$1" in
    --)
        done_options=1
        shift
        break
        ;;
    -h*) # Help
        usage
        ;;
    -d) # Truncate hostname
        TRUNCATE=1
        ;;
    -p) # Persistent SSH
        SSHONCE=1
        ;;
    -S) # Script file to run
        [ $# -gt 1 ] || usage "-S requires a script name"
        shift
        USE_FILE="$1"
        ;;
    -f) # Directory of files to upload
        [ $# -gt 1 ] || usage "-f requires a directory location"
        shift
        USE_DIR="$1"
        ;;
    -F) # Single file to upload
        [ $# -gt 1 ] || usage "-F requires a file name"
        shift
        COPY_FILE="$1"
        ;;
    -T) # Temp dir (local and remote) – not implemented yet
        [ $# -gt 1 ] || usage "-T requires a directory name"
        shift
        TEMPDIR="$1"
        ;;
    -*)
        usage "unknown option $1"
        ;;
    esac
    shift
done

# ---[ RUNTIME ]--------------------------------------------------
# Validate parameters for privilege escalation

# Use ControlMaster to make connections persistent
if [ "$SSHONCE" -eq 1 ]; then
    SSH_PARAMS='-o ControlMaster=auto -o ControlPath=/tmp/drist_ssh_%h_%p_%r.sock -o ControlPersist=1m'
fi

# Determine the list of servers
if [ -f "$1" ]; then
    SERVER_LIST="$(tr '\n' ' ' <"$1")"
else
    SERVER_LIST="$@"
fi

if [ -z "${SERVER_LIST}" ]; then
    echo "No server specified"
    exit 1
fi

# -------------------------------------------------------------------------
# Main loop – process each remote server
# -------------------------------------------------------------------------
for remote_server in ${SERVER_LIST}; do
    # Verify that the host is reachable
    HOSTNAME=$(ssh $SSH_PARAMS "${remote_server}" "uname -n")
    if [ $? -ne 0 ]; then
        echo "Error while ssh ${remote_server}"
        exit 2
    fi

    # Optionally strip the domain part
    if [ "$TRUNCATE" -eq 1 ]; then
        HOSTNAME="${HOSTNAME%%.*}"
    fi


    # Upload directories/files
    copy_files "${USE_DIR}" "${remote_server}" "$TEMPDIR"
    copy_files "${USE_DIR}-${HOSTNAME}" "${remote_server}" "$TEMPDIR"
    copy_single_file "${COPY_FILE}" "${remote_server}" "$TEMPDIR"
    copy_single_file "${COPY_FILE}-${HOSTNAME}" "${remote_server}" "$TEMPDIR"
    # Run the remote script(s)
    remote_script "${USE_FILE}" "${remote_server}" "$TEMPDIR" ${ESCALATED_PRIVILEGES}
    remote_script "${USE_FILE}-${HOSTNAME}" "${remote_server}" "$TEMPDIR" ${ESCALATED_PRIVILEGES}
    # Clean‑up
    delete_temp "${remote_server}" "$TEMPDIR"

    # Close the persistent socket if we opened one
    if [ "$SSHONCE" -eq 1 ]; then
        ssh $SSH_PARAMS -O exit -N "${remote_server}"
    fi

    unset TEMPDIR HOSTNAME
done
